name: Update trackers list

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: read

jobs:
  update-list:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        pip install requests==2.31.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update lists
      run: |
        set -euo pipefail
        python3 generate_list.py
    - name: Commit and push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -euo pipefail
        cd release
        git init
        git config --local user.email "github-action@users.noreply.github.com"
        git config --local user.name "GitHub Action"
        git remote add origin https://github-action:$GITHUB_TOKEN@github.com/Phoroc/adg-trackerlist.git
        git branch -M release
        git add .
        git commit --allow-empty-message --no-edit
        git push -f origin release
